"""Deterministic routing rules for task classification."""
from src.models.enums import TaskCategory
from src.routing.models import RoutingRule

# High-confidence keyword rules for each category
ROUTING_RULES: list[RoutingRule] = [
    # Mathematical Reasoning
    RoutingRule(
        category=TaskCategory.MATHEMATICAL_REASONING,
        keywords=[
            "calculate",
            "compute",
            "solve",
            "equation",
            "math",
            "mathematics",
            "arithmetic",
            "algebra",
            "geometry",
            "calculus",
            "derivative",
            "integral",
            "probability",
            "statistics",
            "number",
            "sum",
            "product",
            "divide",
            "multiply",
            "subtract",
            "add",
        ],
        phrases=[
            "what is",
            "how many",
            "how much",
            "find the value",
            "solve for",
            "calculate the",
        ],
        weight=1.5,
    ),
    # Code Generation
    RoutingRule(
        category=TaskCategory.CODE_GENERATION,
        keywords=[
            "write",
            "create",
            "implement",
            "generate",
            "code",
            "function",
            "class",
            "method",
            "program",
            "script",
            "algorithm",
            "develop",
            "build",
        ],
        phrases=[
            "write a function",
            "create a class",
            "implement a",
            "write code",
            "create code",
            "generate code",
            "write a program",
            "write a script",
        ],
        weight=1.5,
    ),
    # Code Debugging
    RoutingRule(
        category=TaskCategory.CODE_DEBUGGING,
        keywords=[
            "debug",
            "fix",
            "error",
            "bug",
            "issue",
            "problem",
            "wrong",
            "incorrect",
            "broken",
            "crash",
            "exception",
            "traceback",
        ],
        phrases=[
            "fix the code",
            "debug this",
            "what's wrong",
            "find the bug",
            "fix the bug",
            "find the error",
        ],
        weight=1.5,
    ),
    # Sentiment Classification
    RoutingRule(
        category=TaskCategory.SENTIMENT,
        keywords=[
            "sentiment",
            "emotion",
            "feeling",
            "positive",
            "negative",
            "neutral",
            "mood",
            "tone",
            "opinion",
        ],
        phrases=[
            "classify sentiment",
            "analyze sentiment",
            "determine sentiment",
            "sentiment analysis",
            "positive or negative",
        ],
        weight=2.0,
    ),
    # Named Entity Recognition
    RoutingRule(
        category=TaskCategory.NAMED_ENTITY_RECOGNITION,
        keywords=[
            "extract",
            "identify",
            "find",
            "entity",
            "entities",
            "name",
            "names",
            "person",
            "organization",
            "location",
            "date",
            "ner",
        ],
        phrases=[
            "extract entities",
            "identify entities",
            "find entities",
            "named entity",
            "extract names",
            "identify names",
        ],
        weight=2.0,
    ),
    # Text Summarization
    RoutingRule(
        category=TaskCategory.SUMMARIZATION,
        keywords=[
            "summarize",
            "summary",
            "brief",
            "concise",
            "overview",
            "abstract",
            "condense",
            "shorten",
            "main points",
            "key points",
        ],
        phrases=[
            "summarize the",
            "provide a summary",
            "give a summary",
            "write a summary",
            "create a summary",
            "main points of",
        ],
        weight=2.0,
    ),
    # Logical Reasoning
    RoutingRule(
        category=TaskCategory.LOGICAL_REASONING,
        keywords=[
            "logic",
            "logical",
            "reasoning",
            "deduce",
            "infer",
            "conclude",
            "therefore",
            "because",
            "if",
            "then",
            "syllogism",
            "premise",
            "conclusion",
        ],
        phrases=[
            "logical reasoning",
            "deduce from",
            "infer from",
            "conclude that",
            "if then",
        ],
        weight=1.5,
    ),
    # Factual Knowledge (catch-all for questions)
    RoutingRule(
        category=TaskCategory.FACTUAL_KNOWLEDGE,
        keywords=[
            "what",
            "who",
            "when",
            "where",
            "which",
            "why",
            "how",
            "is",
            "are",
            "was",
            "were",
            "define",
            "definition",
            "explain",
            "describe",
        ],
        phrases=[
            "what is",
            "who is",
            "when did",
            "where is",
            "tell me about",
            "explain the",
        ],
        weight=0.8,  # Lower weight since it's a catch-all
    ),
]


def get_rules_for_category(category: TaskCategory) -> list[RoutingRule]:
    """Get all routing rules for a specific category."""
    return [rule for rule in ROUTING_RULES if rule.category == category]
